name: run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  # code coverage job
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.3.0

      - name: Run Tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: '--out Xml --locked --jobs 16 --timeout 3600 --skip-clean -- --test-threads 16 '

      - name: Upload CodeCov
        uses: codecov/codecov-action@v2